// Reverse-engineered syllabus chapter lists per target exam.

export type ExamSyllabus = {
  id: string;
  name: string;
  chapters: string[];
};

export const EXAM_SYLLABI: ExamSyllabus[] = [
  {
    id: "jee-main",
    name: "JEE Main",
    chapters: [
      "Sets, Relations and Functions",
      "Complex Numbers & Quadratic Equations",
      "Matrices and Determinants",
      "Permutations and Combinations",
      "Binomial Theorem",
      "Sequence and Series",
      "Limits, Continuity and Differentiability",
      "Application of Derivatives",
      "Integral Calculus",
      "Differential Equations",
      "Coordinate Geometry (2D)",
      "3D Geometry and Vectors",
      "Probability",
      "Trigonometry",
      "Statistics",
      "Physics: Kinematics",
      "Physics: Laws of Motion",
      "Physics: Work, Energy and Power",
      "Physics: Rotational Motion",
      "Physics: Gravitation",
      "Physics: Thermodynamics",
      "Physics: Oscillations and Waves",
      "Physics: Electrostatics",
      "Physics: Current Electricity",
      "Physics: Magnetic Effects of Current",
      "Physics: EMI and AC",
      "Physics: Optics",
      "Physics: Modern Physics",
      "Chemistry: Atomic Structure",
      "Chemistry: Chemical Bonding",
      "Chemistry: Thermodynamics",
      "Chemistry: Equilibrium",
      "Chemistry: Redox & Electrochemistry",
      "Chemistry: Chemical Kinetics",
      "Chemistry: Coordination Compounds",
      "Chemistry: GOC + Hydrocarbons",
      "Chemistry: Haloalkanes/Haloarenes",
      "Chemistry: Alcohols, Phenols, Ethers",
      "Chemistry: Aldehydes, Ketones, Acids",
      "Chemistry: Biomolecules & Polymers",
    ],
  },
  {
    id: "neet",
    name: "NEET",
    chapters: [
      "Physics: Mechanics — Kinematics",
      "Physics: Laws of Motion",
      "Physics: Work, Energy, Power",
      "Physics: Rotational Motion",
      "Physics: Thermodynamics",
      "Physics: Oscillations & Waves",
      "Physics: Electrostatics",
      "Physics: Current Electricity",
      "Physics: Magnetism",
      "Physics: EMI & AC",
      "Physics: Optics",
      "Physics: Modern Physics",
      "Chemistry: Mole Concept",
      "Chemistry: Atomic Structure",
      "Chemistry: Chemical Bonding",
      "Chemistry: Thermodynamics",
      "Chemistry: Equilibrium",
      "Chemistry: Redox",
      "Chemistry: Coordination Compounds",
      "Chemistry: GOC",
      "Chemistry: Hydrocarbons",
      "Chemistry: Alcohols/Phenols/Ethers",
      "Chemistry: Aldehydes/Ketones/Acids",
      "Chemistry: Amines",
      "Chemistry: Biomolecules",
      "Biology: Cell — Unit of Life",
      "Biology: Plant Physiology",
      "Biology: Human Physiology",
      "Biology: Reproduction",
      "Biology: Genetics & Evolution",
      "Biology: Biology in Human Welfare",
      "Biology: Biotechnology",
      "Biology: Ecology",
      "Biology: Diversity of Living Organisms",
      "Biology: Structural Organisation",
    ],
  },
  {
    id: "cbse-12-board",
    name: "CBSE Class 12 Boards",
    chapters: [
      "Physics: Electrostatics",
      "Physics: Current Electricity",
      "Physics: Magnetism",
      "Physics: EMI & AC",
      "Physics: EM Waves",
      "Physics: Optics",
      "Physics: Dual Nature of Matter",
      "Physics: Atoms & Nuclei",
      "Physics: Electronic Devices",
      "Chemistry: Solutions",
      "Chemistry: Electrochemistry",
      "Chemistry: Chemical Kinetics",
      "Chemistry: d & f Block",
      "Chemistry: Coordination Compounds",
      "Chemistry: Haloalkanes",
      "Chemistry: Alcohols/Phenols/Ethers",
      "Chemistry: Aldehydes/Ketones/Acids",
      "Chemistry: Amines",
      "Chemistry: Biomolecules",
      "Maths: Relations & Functions",
      "Maths: Inverse Trig",
      "Maths: Matrices & Determinants",
      "Maths: Continuity & Differentiability",
      "Maths: Application of Derivatives",
      "Maths: Integrals",
      "Maths: Application of Integrals",
      "Maths: Differential Equations",
      "Maths: Vectors & 3D",
      "Maths: Linear Programming",
      "Maths: Probability",
    ],
  },
];

export function getSyllabus(id: string) {
  return EXAM_SYLLABI.find((e) => e.id === id) ?? null;
}
