// Full Telangana SCERT chapter lists (Classes 6–10) + Intermediate (TSBIE).
// Used by the Focus Timer so every lesson of a subject is selectable.

import { INTER_MPC_VAULT } from "@/lib/inter-mpc-data";
import { INTER_BPC_VAULT } from "@/lib/inter-bipc-data";

export type SyllabusMap = Record<string, Record<string, string[]>>;

const SCHOOL: SyllabusMap = {
  "10": {
    Mathematics: [
      "Real Numbers",
      "Sets",
      "Polynomials",
      "Pair of Linear Equations in Two Variables",
      "Quadratic Equations",
      "Progressions",
      "Coordinate Geometry",
      "Similar Triangles",
      "Tangents and Secants to a Circle",
      "Mensuration",
      "Trigonometry",
      "Applications of Trigonometry",
      "Probability",
      "Statistics",
    ],
    "Physical Science": [
      "Heat",
      "Chemical Equations",
      "Acids, Bases and Salts",
      "Refraction of Light at Plane Surfaces",
      "Refraction of Light at Curved Surfaces",
      "Human Eye and Colourful World",
      "Structure of Atom",
      "Classification of Elements — The Periodic Table",
      "Chemical Bonding",
      "Electric Current",
      "Electromagnetism",
      "Principles of Metallurgy",
      "Carbon and its Compounds",
    ],
    "Biological Science": [
      "Nutrition — The Food Supplying System",
      "Respiration — The Energy Releasing System",
      "Transportation — The Circulatory System",
      "Excretion — The Wastage Disposing System",
      "Coordination — The Linking System",
      "Reproduction — The Generating System",
      "Heredity — From Parent to Progeny",
      "Our Environment — Our Concern",
      "Natural Resources",
    ],
    "Social Studies": [
      "India: Relief Features",
      "Ideas of Development",
      "Production and Employment",
      "Climate of India",
      "Indian Rivers and Water Resources",
      "The People",
      "People and Settlement",
      "People and Migration",
      "Rampur — A Village Economy",
      "Globalisation",
      "Food Security",
      "Sustainable Development with Equity",
      "The World Between Wars 1900–1950",
      "National Liberation Movements in the Colonies",
      "National Movement in India 1919–1947",
      "The Making of Independent India's Constitution",
      "Election Process in India",
      "Independent India — The First 30 Years",
      "Emerging Political Trends 1977–2000",
      "Post-War World and India",
      "Social Movements in Our Times",
      "The Movement for the Formation of Telangana State",
    ],
    English: [
      "Personality Development",
      "Wit and Humour",
      "Human Relations",
      "Films and Theatre",
      "Bio-Diversity",
      "Nation and Diversity",
      "Human Rights",
      "Sports and Games",
    ],
  },
  "9": {
    Mathematics: [
      "Real Numbers",
      "Polynomials and Factorisation",
      "The Elements of Geometry",
      "Lines and Angles",
      "Co-ordinate Geometry",
      "Linear Equations in Two Variables",
      "Triangles",
      "Quadrilaterals",
      "Statistics",
      "Surface Areas and Volumes",
      "Areas",
      "Circles",
      "Geometrical Constructions",
      "Probability",
      "Proofs in Mathematics",
    ],
    "Physical Science": [
      "Matter Around Us",
      "Motion",
      "Laws of Motion",
      "Is Matter Pure?",
      "Atoms and Molecules",
      "What is Inside the Atom?",
      "Reflection of Light at Curved Surfaces",
      "Gravitation",
      "Floating Bodies",
      "Work and Energy",
      "Heat",
      "Sound",
      "Chemical Reactions and Equations",
    ],
    "Biological Science": [
      "Cell — Its Structure and Functions",
      "Plant Tissues",
      "Animal Tissues",
      "Plasma Membrane",
      "Diversity in Living Organisms",
      "Sense Organs",
      "Animal Behaviour",
      "Challenges in Improving Agricultural Products",
      "Adaptations in Different Ecosystems",
      "Soil Pollution",
      "Bio-Geo Chemical Cycles",
      "Our Environment",
      "Why Do We Fall Ill",
    ],
    "Social Studies": [
      "Our Earth",
      "The Natural Realms of the Earth",
      "Hydrosphere",
      "Atmosphere",
      "Biosphere",
      "Agriculture in India",
      "Industries in India",
      "Service Activities in India",
      "Credit in the Financial System",
      "Prices and Cost of Living",
      "The Government Budget and Taxation",
      "Democracy — An Evolving Idea",
      "Colonialism in Latin America, Asia and Africa",
      "Impact of Colonialism in India",
      "Expansion of Democracy",
      "Democracy in the Contemporary World",
      "Human Rights and Fundamental Rights",
      "Traffic Education",
      "Disaster Management",
    ],
  },
  "8": {
    Mathematics: [
      "Rational Numbers",
      "Linear Equations in One Variable",
      "Construction of Quadrilaterals",
      "Exponents and Powers",
      "Comparing Quantities Using Proportion",
      "Square Roots and Cube Roots",
      "Frequency Distribution Tables and Graphs",
      "Exploring Geometrical Figures",
      "Area of Plane Figures",
      "Direct and Inverse Proportions",
      "Algebraic Expressions",
      "Factorisation",
      "Visualising 3-D in 2-D",
      "Surface Area and Volume (Cube–Cuboid)",
      "Playing with Numbers",
    ],
    "Physical Science": [
      "Force",
      "Friction",
      "Synthetic Fibres and Plastics",
      "Metals and Non-Metals",
      "Coal and Petroleum",
      "Combustion, Fuels and Flame",
      "Sound",
      "Electrical Conductivity of Liquids",
      "Some Natural Phenomena",
      "Stars and the Solar System",
    ],
    "Biological Science": [
      "What is Science",
      "Cell — The Basic Unit of Life",
      "Microorganisms",
      "Reproduction in Animals",
      "Reaching the Age of Adolescence",
      "Biosphere",
      "Conservation of Plants and Animals",
      "Production of Food from Plants",
      "Production of Food from Animals",
    ],
    "Social Studies": [
      "Reading and Analysis of Maps",
      "Energy from the Sun",
      "Earth Movements and Seasons",
      "Hydrosphere",
      "Biosphere",
      "Landforms",
      "Rocks and Minerals",
      "Agriculture in Asia",
      "Industries in Asia",
      "Colonialism in India",
      "Rise of Nationalism",
      "Freedom Movement 1919–1947",
      "The Indian Constitution",
      "Parliament and Central Government",
      "Law and Justice",
      "Understanding Poverty",
      "Handicrafts and Handlooms",
      "Land, Soil and Water Resources",
    ],
  },
  "7": {
    Mathematics: [
      "Integers",
      "Fractions, Decimals and Rational Numbers",
      "Simple Equations",
      "Lines and Angles",
      "Triangle and Its Properties",
      "Ratio — Applications",
      "Data Handling",
      "Congruency of Triangles",
      "Construction of Triangles",
      "Algebraic Expressions",
      "Exponents and Powers",
      "Quadrilaterals",
      "Area and Perimeter",
      "Understanding 3D and 2D Shapes",
      "Symmetry",
    ],
    "Physical Science": [
      "Food Components",
      "Acids and Bases",
      "Physical and Chemical Changes",
      "Motion and Time",
      "Heat — Measurement",
      "Electricity — Current and Its Effect",
      "Air, Winds and Cyclones",
      "Water",
      "Fibre to Fabric",
      "Soil",
    ],
    "Biological Science": [
      "Nutrition in Plants",
      "Nutrition in Animals",
      "Respiration in Organisms",
      "Transportation in Plants and Animals",
      "Reproduction in Plants",
      "Weather and Climate",
      "Forests — Our Life",
      "Waste Water Management",
      "Changes Around Us",
    ],
    "Social Studies": [
      "Reading Maps of Different Kinds",
      "Rain and Rivers",
      "Tanks and Ground Water",
      "Oceans and Fishing",
      "Europe",
      "Africa",
      "Handicrafts and Handlooms",
      "Industries in Asia",
      "New Kings and Kingdoms",
      "The Kakatiyas",
      "Delhi Sultans",
      "Mughal Empire",
      "Establishment of the British Empire",
      "Making of Laws in the State Assembly",
      "Implementation of Laws in the State",
      "Caste Discrimination",
      "Livelihood and Struggles of Urban Workers",
      "Media and Democracy",
    ],
  },
  "6": {
    Mathematics: [
      "Knowing Our Numbers",
      "Whole Numbers",
      "Playing with Numbers",
      "Basic Geometrical Ideas",
      "Measures of Lines and Angles",
      "Integers",
      "Fractions and Decimals",
      "Data Handling",
      "Introduction to Algebra",
      "Perimeter and Area",
      "Ratio and Proportion",
      "Symmetry",
      "Practical Geometry",
      "Understanding 3D and 2D Shapes",
    ],
    "Physical Science": [
      "Our Food",
      "Playing with Magnets",
      "Rain — Where Does It Come From?",
      "Materials and Things",
      "Separation of Substances",
      "Water",
      "Air Around Us",
      "Measurements and Motion",
      "Light, Shadows and Images",
      "Electricity and Circuits",
    ],
    "Biological Science": [
      "Getting to Know Plants",
      "Parts of a Plant and Their Functions",
      "Living and Non-Living",
      "Habitat",
      "Body Movements",
      "Food Habits of Animals",
      "Our Health",
      "The World of Living",
    ],
    "Social Studies": [
      "Diversity on the Earth",
      "Globe — A Model of the Earth",
      "Maps",
      "Land Forms",
      "Basic Concepts in Geography",
      "Agriculture",
      "Village Panchayat",
      "Local Self Government in Urban Areas",
      "Rural Livelihoods",
      "Urban Livelihoods",
      "The Earliest Societies",
      "The First Farmers and Herders",
      "The First Cities",
      "The Vedic Period",
      "Religious Reformers",
      "Emergence of Kingdoms and Republics",
    ],
  },
};

function interSubjects(year: "1st Year" | "2nd Year"): Record<string, string[]> {
  const out: Record<string, string[]> = {};
  for (const book of [...INTER_MPC_VAULT, ...INTER_BPC_VAULT]) {
    if (book.year !== year || book.medium !== "English") continue;
    out[book.subject] = book.chapters.map((c) => c.title);
  }
  return out;
}

export const SYLLABUS_CHAPTERS: SyllabusMap = {
  ...SCHOOL,
  "Inter 1st Year": interSubjects("1st Year"),
  "Inter 2nd Year": interSubjects("2nd Year"),
};

export const CLASS_KEYS = Object.keys(SYLLABUS_CHAPTERS);

export function classLabel(key: string) {
  return /^\d+$/.test(key) ? `Class ${key}` : key;
}

export function totalChapterCount() {
  let n = 0;
  for (const subjects of Object.values(SYLLABUS_CHAPTERS)) {
    for (const chapters of Object.values(subjects)) n += chapters.length;
  }
  return n;
}
